syntax on
set number
set expandtab
set tabstop=4
set shiftwidth=0
set autoindent
set smartindent
set foldmethod=indent
set foldnestmax=10
set clipboard=unnamedplus
set hlsearch
set incsearch
hi Search ctermfg=brown guifg=brown
hi Folded ctermfg=white guifg=white

call plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'habamax/vim-sendtoterm'
Plug 'github/copilot.vim'
Plug 'zah/nim.vim'
call plug#end()

nnoremap ;t :NERDTreeToggle<CR>
nnoremap ;r :execute 'vertical terminal ' . input("REPL program (blank for terminal): ")<CR>
nnoremap ;hr :execute 'terminal ' . input("REPL program (blank for terminal): ")<CR>
nnoremap ;<Left> :tabp<CR>
nnoremap ;<Right> :tabn<CR>
nnoremap ;s <Plug>(SendToTerm)
xnoremap ;s <Plug>(SendToTerm)
nnoremap ;ss <Plug>(SendToTermLine)
nnoremap <S-Up> <C-w>k
nnoremap <S-Down> <C-w>j
nnoremap <S-Left> <C-w>h
nnoremap <S-Right> <C-w>l
nnoremap `<Up> :resize +1<CR>
nnoremap `<Down> :resize -1<CR>
nnoremap `<Left> :vertical resize -1<CR>
nnoremap `<Right> :vertical resize +1<CR>

imap <C-k> <Plug>(copilot-accept-word)
imap <C-l> <Plug>(copilot-accept-line)
imap <C-j> <Plug>(copilot-next)
imap <C-;> <Plug>(copilot-previous)

